### ISSUE TITLE
 POJO-Generator call during the build

### ISSUE THREAD

**Issue by MarErm27** [Jukien/POJO-Generator#15]
Hello!
How to call POJO-Generator during the build of the maven project?

**Comment by Jukien** [comment]
Hi @MarErm27, may I ask why you want to do that?
POJO Generator was created to facilitate the writing of JPA Entity files.

**Comment by MarErm27** [comment]
> 
> 
> Hi @MarErm27, may I ask why you want to do that?
> POJO Generator was created to facilitate the writing of JPA Entity files.

Hi, please ask everything you need!
I'm not allowed to spend any time to change classes when the database changes. This is a condition that my team leader gave me. I must to provide automatic database and entity classes generation during the build of the project with MySQL script or anyhow else. I generate the database with Flyway but sadly it does not generate the classes. Please, help

**Comment by Jukien** [comment]
@MarErm27 I don't see the goal to generate entity classes during the build. These files need to be generated once, maintained and customized depending on how you want to use these entities in your project.
POJO Generator hasn't this purpose to be used with Maven or maybe I misunderstood :s

**Comment by MarErm27** [comment]
> @MarErm27 I don't see the goal to generate entity classes during the build. These files need to be generated once, maintained and customized depending on how you want to use these entities in your project.
> POJO Generator hasn't this purpose to be used with Maven or maybe I misunderstood :s

You got it right. I'm not allowed to store entity classes in the repository so I have to generate them during the build

**Comment by Jukien** [comment]
@MarErm27 ok but I can't help you with the plugin.
It's not the primary goal of POJO Generator and what you want doesn't fit with what I created, sorry.
