### ISSUE TITLE
composite primary keys not managed properly?!

### ISSUE THREAD

**Issue by XSven** [Jukien/POJO-Generator#17]
The **User** POJO example mentioned in the _README.md_ documentation has a simple primary key. We wanted to apply the POJO generator to a table that has a composite primary key. The POJO generator correctly annotates the corresponding fields with `@Id` ,  but it does not autogenerate a corresponding **serializable** ID class that should be the value of the `@IdClass` annotation that is missing too in our POJO. There exists at least a second way to manage ID classes. This way is based on the `@Embeddable` and  `@EmbeddedId` annotations. I have the feeling that this second way is more complicated to implement, so I would be glad if at least the first approach could be implemented.

**Comment by Jukien** [comment]
Hi @XSven, thank you for using POJO Generator!
Indeed, I rarely use composite primary keys so I didn't managed it. But if you have this need let me check the feasibility.
Maybe I will have some questions and need your help to test it in real world.
I'll keep you informed.

**Comment by Jukien** [comment]
Hi @XSven, can you check [this version](https://github.com/Jukien/POJO-Generator/releases/download/v2.3.0-beta-1/pojo-generator-2.3.0-beta-1.zip) and tell me if it's what you need?

*You can go [here](https://plugins.jetbrains.com/plugin/12297-pojo-generator/versions/beta) to download the beta or add this url: https://plugins.jetbrains.com/plugins/beta/12297 in Settings > Plugins > Manage Plugin Repositories.*
