### ISSUE TITLE
composite primary keys JPA compliance and no specifics of JPA providers like Hibernate

### ISSUE THREAD

**Issue by XSven** [Jukien/POJO-Generator#20]
Sorry for being late to provide feedback with respect to the composite primary key enhancement (issue #17). I have tested the @IdClass approach and it seems to works. But:

Section 2.4 of the JPA 2.1 specification defines the rules for composite primary keys. One such rule requires to override equals() and hashCode(). The JPA specification says nothing about getters and setters. Furthermore the all args constructor of the id class seems to be logical to me but JPA does not mandate this. I have the feeling that the generated id class is influenced by the choice of a JPA provider like Hibernate. Maybe you could comment on that.

**Comment by Jukien** [comment]
Hi @XSven, it's okay.
I searched several examples on the internet and I did what was the most common based on the internet examples.
Maybe I can propose to add the all args constructor and getter/setter in the options. What do you think?
Have you tried with the Embeddable annotation?
