### ISSUE TITLE
Support for Project Lombok

### ISSUE THREAD

**Issue by harinath2007** [Jukien/POJO-Generator#21]
Add ** At Data** Annotation to the class  and  do not generate getters and setters.

**Comment by Jukien** [comment]
Hi @harinath2007, I'm kind busy at this time but I keep your evolution request in mind.

**Comment by Jukien** [comment]
Fixed in version [2.6.0](https://plugins.jetbrains.com/plugin/12297-pojo-generator/versions/stable/586283)
