### ISSUE TITLE
Not support below types in postgresql

### ISSUE THREAD

**Issue by gaoxingliang** [Jukien/POJO-Generator#23]
1. number (8, 2)
2. timestamp with timezone
3. text
4. uuid

I will fix this issue.

**Comment by Jukien** [comment]
Hi @gaoxingliang, updating the JPA Mapping table isn't enough?

**Comment by gaoxingliang** [comment]
@Jukien Yes. it's working. I missed the settings in idea.
Paste a list of what I'm using just in case someone got same issue
<img width="787" alt="图片" src="https://user-images.githubusercontent.com/3148215/98886114-53a33580-24ce-11eb-9e26-5d1798680791.png">

**Comment by gaoxingliang** [comment]
it's under intellij -> preferences:
<img width="416" alt="图片" src="https://user-images.githubusercontent.com/3148215/98886155-70d80400-24ce-11eb-9fc3-71500daf5694.png">

**Comment by Jukien** [comment]
@gaoxingliang ok perfect.
Have a nice day!
