### ISSUE TITLE
Please add Postgres mapping "text"->"String","double precision"->"Double","smallint"->"Short"

### ISSUE THREAD

**Issue by errorman-awful** [Jukien/POJO-Generator#24]

**Comment by Jukien** [comment]
Hi @WinnerSonX, there is a JPA mapping table customizable in the settings. Is that fitting your needs?

**Comment by errorman-awful** [comment]
> Hi @WinnerSonX, there is a JPA mapping table customizable in the settings. Is that fitting your needs?

Sorry, i didnt know about that setting,so my problem is solved

**Comment by Jukien** [comment]
@WinnerSonX ok perfect. I will improve the description for the existence of the settings.
