### ISSUE TITLE
Sql Server

### ISSUE THREAD

**Issue by thomassamoul** [Jukien/POJO-Generator#27]
Can u support SQL SERVER ?

**Comment by Jukien** [comment]
Hi @thomassamoul, I have to look into it to see if it doesn't take me too much time. Give me the month and I will get back to you.

**Comment by Jukien** [comment]
Hi @thomassamoul, I released a new version with the Sql Server support. You can test it [here](https://github.com/Jukien/POJO-Generator/releases/download/v2.5.0/pojo-generator-2.5.0.zip) in advance.
It will be available for everyone in few days.
If something doesn't work as expected, feel free to get back to me.
Have a nice day!
