### ISSUE TITLE
relations between entities

### ISSUE THREAD

**Issue by 0pipe0** [Jukien/POJO-Generator#3]
You shoud implement a way to generate relations by inspecting table's FKs.

**Comment by Jukien** [comment]
Hi @0pipe0, sorry for the delay.

I think it's a lot of work for a benefit which will not be so important.

I mean how do you want to use this feature?

First, it's useful when you need to create from scratch all entities to generate all relationships. But after that, your application change and you will need to add one by one the entities and update others to add manually relationships.

Second, relationship depends on each context of use of the application. I think for many cases, `@ManyToOne` is applied but sometime you want `@OneToOne` for example. And for relationship you need to add sometime characteristics like `cascade`, `orphanRemoval`, etc...

So at this end you are going to adapt the generated file with you own characteristics and requirements.

What I can do it's to add automatically `@ManyToOne` and `@JoinColumn` annotation when the column has a foreign key to save writing time (#8) but to do more than that is to make decisions for others I think.

Happy to discuss about it and Happy New Year!
